name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-pr:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Test
        run: |
            bun install
            bunx playwright install
            bun run build
            bun run test
